services:
  postgres:
    image: postgres:17-alpine
    container_name: sable_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sable
    ports:
      - "5432:5432"
    volumes:
      - sable_postgres_data:/var/lib/postgresql/data

volumes:
  sable_postgres_data:
    driver: local
